<e>   ::= add(<e>,<e>)|sub(<e>,<e>)|mul(<e>,<e>)|pdiv(<e>,<e>)|psqrt(<e>)|np.sin(<e>)|np.tanh(<e>)|plog(<e>)|add(<e>,<e>)|sub(<e>,<e>)|mul(<e>,<e>)|pdiv(<e>,<e>)|psqrt(<e>)|np.sin(<e>)|np.tanh(<e>)|plog(<e>)|x[1]|x[2]|x[3]|x[4]|x[5]|x[6]|x[7]|x[8]|x[9]|x[10]|x[11]|x[12]|x[13]|x[14]|<c><c>.<c><c>|<c><c>.<c><c>|<c><c>.<c><c>|<c><c>.<c><c>|<c><c>.<c><c>
<c>  ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
