<e>  ::=  <e>+<e>|
          <e>-<e>|
          <e>*<e>|
          pdiv(<e>,<e>)|
          psqrt(<e>)|
          np.sin(<e>)|
          np.tanh(<e>)|
          exp(<e>)|
          plog(<e>)|
          x[0]|x[1]|x[2]|x[3]|x[4]|
          <c><c>.<c><c>
<c>  ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9

